apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
  - image: ubuntu-sleeper
    name: ubuntu-sleeper
    # overrides the entrypoint instruction 
    command: ["echo"]  
    # overrieds the commad instruction  
    args: ["10"]