apiVersion: v1
kind: Pod
metadata:
  name: app-1
  labels:
    app: app-1
    function: front-end
spec:
  containers:
  - name: nginx-app-1
    image: nginx:1.7.9
    ports:
    - containerPort: 8080
