apiVersion: v1
kind: Service
metadata:
  name: pay-service
  namespace: critical-space
spec:
  clusterIP: 10.102.93.253
  clusterIPs:
  - 10.102.93.253
  ipFamilies:
  - IPv4
  ports:
  - port: 8282
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp-pay
  type: ClusterIP