apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
spec:
  containers:
    - name: web-app
      image: web-app
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080

        # for tcp
        # tcpSocket:
        #   port: 8080
       
        # for exec
        # exec:
        #   command:
        #     - cat
        #     - /tmp/healthy
        
        initialDelaySeconds: 5
        periodSeconds: 5