apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: configmap-container
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sample-config
            