apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  containers:
    - name: nginx-bee
      image: nginx
  tolerations:
    - key: spray
      opertator: "Equal"
      value: mortein
      effect: NoSchedule